modLoader="javafml"
loaderVersion="[4,)"
license="${license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
credits="${credits}"
displayURL="${mod_homepage}"
issueTrackerURL="${mod_issues}"
logoFile="assets/cobblemon_riding_tweaks/icon.png"
description='''${description}'''

[[mixins]]
config = "cobblemon_riding_tweaks.mixins.json"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobblemon"
type="required"
versionRange="[${cobblemon_version},)"
ordering="AFTER"
side="BOTH"

[features.${mod_id}]
javaVersion="[${java_version},)"
